#include <stdio.h>
#include "attendence_2.h"
int attendence_1(int rollno)
{
	int roll=rollno;
	float attendence=30;
	switch(roll)
	{
		case 1 : attendence;
				 return(attendence);
		case 2 : attendence;
				 return(attendence);
		case 3 : attendence;
				 return(attendence);
		case 4 : attendence;
				 return(attendence);
		case 5 : attendence;
				 return(attendence);
		case 6 : attendence;
				 return(attendence);
		case 7 : attendence;
				 return(attendence);
		case 8 : attendence;
				 return(attendence);
		case 9 : attendence;
				 return(attendence);
		case 10: attendence;
				 return(attendence);
		case 11: attendence;
				 return(attendence);
		case 12: attendence;
				 return(attendence);
		case 13: attendence;
				 return(attendence);
		case 14: attendence;
				 return(attendence);
		case 15: attendence;
				 return(attendence);
		case 16: attendence;
				 return(attendence);
		case 17: attendence;
				 return(attendence);
		case 18: attendence;
				 return(attendence);
		case 19: attendence;
				 return(attendence);
		case 20: attendence;
				 return(attendence);
		case 21: attendence;
				 return(attendence);
		case 22: attendence;
				 return(attendence);
		case 23: attendence;
				 return(attendence);
		case 24: attendence;
				 return(attendence);
		case 25: attendence;
				 return(attendence);
		case 26: attendence;
				 return(attendence);
		case 27: attendence;
				 return(attendence);
		case 28: attendence;
				 return(attendence);
		case 29: attendence;
				 return(attendence);
		case 30: attendence;
				 return(attendence);
		case 31: attendence;
				 return(attendence);
		case 32: attendence;
				 return(attendence);
		case 33: attendence;
				 return(attendence);
		case 34: attendence;
				 return(attendence);
		case 35: attendence;
				 return(attendence);
		case 36: attendence;
				 return(attendence);
		case 37: attendence;
				 return(attendence);
		case 38: attendence;
				 return(attendence);
		case 39: attendence;
				 return(attendence);
		case 40: attendence;
				 return(attendence);
		case 41: attendence;
				 return(attendence);
		case 42: attendence;
				 return(attendence);
		case 43: attendence;
				 return(attendence);
		case 44: attendence;
				 return(attendence);
		case 45: attendence;
				 return(attendence);
		case 46: attendence;
				 return(attendence);
		case 47: attendence;
				 return(attendence);
		case 48: attendence;
				 return(attendence);
		case 49: attendence;
				 return(attendence);
		case 50: attendence;
				 return(attendence);
		default :attendence_2(rollno);
	}
}