#include <stdio.h>
#include "attendence_3.h"
int attendence_2(int rollno)
{
	
	int roll=rollno;
	float attendence=30;
	switch(rollno)
	{
		case 51: attendence;				 
				 return(attendence);
		case 52: attendence;				 
				 return(attendence);
		case 53: attendence;				 
				 return(attendence);
		case 54: attendence;				 
				 return(attendence);
		case 55: attendence;				 
				 return(attendence);
		case 56: attendence;				 
				 return(attendence);
		case 57: attendence;				 
				 return(attendence);
		case 58: attendence;				 
				 return(attendence);
		case 59: attendence;				 
				 return(attendence);
		case 60: attendence;				 
				 return(attendence);
		case 61: attendence;				 
				 return(attendence);
		case 62: attendence;				 
				 return(attendence);
		case 63: attendence;				 
				 return(attendence);
		case 64: attendence;				 
				 return(attendence);
		case 65: attendence;				 
				 return(attendence);
		case 66: attendence;				 
				 return(attendence);
		case 67: attendence;				 
				 return(attendence);
		case 68: attendence;				 
				 return(attendence);
		case 69: attendence;				 
				 return(attendence);
		case 70: attendence;				 
				 return(attendence);
		case 71: attendence;				 
				 return(attendence);
		case 72: attendence;				 
				 return(attendence);
		case 73: attendence;				 
				 return(attendence);
		case 74: attendence;				 
				 return(attendence);
		case 75: attendence;				 
				 return(attendence);
		case 76: attendence;				 
				 return(attendence);
		case 77: attendence;				 
				 return(attendence);
		case 78: attendence;				 
				 return(attendence);
		case 79: attendence;				 
				 return(attendence);
		case 80: attendence;				 
				 return(attendence);
		case 81: attendence;				 
				 return(attendence);
		case 82: attendence;				 
				 return(attendence);
		case 83: attendence;				 
				 return(attendence);
		case 84: attendence;				 
				 return(attendence);
		case 85: attendence;				 
				 return(attendence);
		case 86: attendence;				 
				 return(attendence);
		case 87: attendence;				 
				 return(attendence);
		case 88: attendence;				 
				 return(attendence);
		case 89: attendence;				 
				 return(attendence);
		case 90: attendence;				 
				 return(attendence);
		case 91: attendence;				 
				 return(attendence);
		case 92: attendence;				 
				 return(attendence);
		case 93: attendence;				 
				 return(attendence);
		case 94: attendence;				 
				 return(attendence);
		case 95: attendence;				 
				 return(attendence);
		case 96: attendence;				 
				 return(attendence);
		case 97: attendence;				 
				 return(attendence);
		case 98: attendence;				 
				 return(attendence);
		case 99: attendence;				 
				 return(attendence);
		case 100:attendence;				 
				 return(attendence);
		default :attendence_3(rollno);
	}
	return(attendence);
}