#include <stdio.h>
int list_3(int rollno)
{
	float marks,attendence;
	switch(rollno)
	{
		case 101: marks=8;
				  attendence=;
				  break;
		case 102: marks=0;
				  attendence=;
				  break;
		case 103: marks=7;
				  attendence=;
				  break;
		case 104: marks=4;
				  attendence=;
				  break;
		case 105: marks=9;
				  attendence=;
				  break;
		case 106: marks=3;
				  attendence=;
				  break;
		case 107: marks=8;
				  attendence=;
				  break;
		case 108: marks=4;
				  attendence=;
				  break;
		case 109: marks=10;
				  attendence=;
				  break;
		case 110: marks=6;
				  attendence=;
				  break;
		case 111: marks=0;
				  attendence=;
				  break;
		case 112: marks=6;
				  attendence=;
				  break;
		case 113: marks=0;
				  attendence=;
				  break;
		case 114: marks=3;
				  attendence=;
				  break;
		case 115: marks=0;
				  attendence=;
				  break;
		case 116: marks=0;
				  attendence=;
				  break;
		case 117: marks=0;
				  attendence=;
				  break;
		case 118: marks=0;
				  attendence=;
				  break;
		case 119: marks=0;
				  attendence=;
				  break;
		case 120: marks=0;
				  attendence=;
				  break;
		case 121: marks=0;
				  attendence=;
				  break;
		case 122: marks=0;
				  attendence=;
				  break;
		case 123: marks=0;
				  attendence=;
				  break;
		case 124: marks=2;
				  attendence=;
				  break;
		case 125: marks=8;
				  attendence=;
				  break;
		case 126: marks=6;
				  attendence=;
				  break;
		case 127: marks=4;
				  attendence=;
				  break;
		case 128: marks=6;
				  attendence=;
				  break;
		case 129: marks=8;
				  attendence=;
				  break;
		case 130: marks=0;
				  attendence=;
				  break;
		case 131: marks=5;
				  attendence=;
				  break;
		case 132: marks=0;
				  attendence=;
				  break;
		case 133: marks=5;
				  attendence=;
				  break;
		case 134: marks=7;
				  attendence=;
				  break;
		default : printf("Your rollno is not on the list!\n");
	}
}