#include <stdio.h>
#include "list_2.h"
int list_1(int rollno)
{
	int marks,attendence;
	switch(rollno)
	{
		case 1 : marks=6;
				 attendence=;
				 break;
		case 2 : marks=7;
				 attendence=;
				 break;
		case 3 : marks=8;
				 attendence=;
				 break;
		case 4 : marks=9;
				 attendence=;
				 break;
		case 5 : marks=10;
				 attendence=;
				 break;
		case 6 : marks=8;
				 attendence=;
				 break;
		case 7 : marks=7;
				 attendence=;
				 break;
		case 8 : marks=9;
				 attendence=;
				 break;
		case 9 : marks=5;
				 attendence=;
				 break;
		case 10: marks=;
				 attendence=;
				 break;
		case 11: marks=;
				 attendence=;
				 break;
		case 12: marks=;
				 attendence=;
				 break;
		case 13: marks=;
				 attendence=;
				 break;
		case 14: marks=;
				 attendence=;
				 break;
		case 15: marks=;
				 attendence=;
				 break;
		case 16: marks=;
				 attendence=;
				 break;
		case 17: marks=;
				 attendence=;
				 break;
		case 18: marks=;
				 attendence=;
				 break;
		case 19: marks=;
				 attendence=;
				 break;
		case 20: marks=;
				 attendence=;
				 break;
		case 21: marks=;
				 attendence=;
				 break;
		case 22: marks=;
				 attendence=;
				 break;
		case 23: marks=;
				 attendence=;
				 break;
		case 24: marks=;
				 attendence=;
				 break;
		case 25: marks=;
				 attendence=;
				 break;
		case 26: marks=;
				 attendence=;
				 break;
		case 27: marks=;
				 attendence=;
				 break;
		case 28: marks=;
				 attendence=;
				 break;
		case 29: marks=;
				 attendence=;
				 break;
		case 30: marks=;
				 attendence=;
				 break;
		case 31: marks=;
				 attendence=;
				 break;
		case 32: marks=;
				 attendence=;
				 break;
		case 33: marks=;
				 attendence=;
				 break;
		case 34: marks=;
				 attendence=;
				 break;
		case 35: marks=;
				 attendence=;
				 break;
		case 36: marks=;
				 attendence=;
				 break;
		case 37: marks=;
				 attendence=;
				 break;
		case 38: marks=;
				 attendence=;
				 break;
		case 39: marks=;
				 attendence=;
				 break;
		case 40: marks=;
				 attendence=;
				 break;
		case 41: marks=;
				 attendence=;
				 break;
		case 42: marks=;
				 attendence=;
				 break;
		case 43: marks=;
				 attendence=;
				 break;
		case 44: marks=;
				 attendence=;
				 break;
		case 45: marks=;
				 attendence=;
				 break;
		case 46: marks=;
				 attendence=;
				 break;
		case 47: marks=;
				 attendence=;
				 break;
		case 48: marks=;
				 attendence=;
				 break;
		case 49: marks=;
				 attendence=;
				 break;
		case 50: marks=;
				 attendence=;
				 break;
		default :list_2(rollno);
	}
}