#include <stdio.h>
#include "list_3.h"
int list_2(int rollno)
{
	float marks,attendence;
	switch(rollno)
	{
		case 51: marks=7;
				 attendence;
				 break;
		case 52: marks=3
				 attendence=;
				 break;
		case 53: marks=8;
				 attendence=;
				 break;
		case 54: marks=1;
				 attendence=;
				 break;
		case 55: marks=1;
				 attendence=;
				 break;
		case 56: marks=5;
				 attendence=;
				 break;
		case 57: marks=6;
				 attendence=;
				 break;
		case 58: marks=9;
				 attendence=;
				 break;
		case 59: marks=5;
				 attendence=;
				 break;
		case 60: marks=7;
				 attendence=;
				 break;
		case 61: marks=8;
				 attendence=;
				 break;
		case 62: marks=9;
				 attendence=;
				 break;
		case 63: marks=9;
				 attendence=;
				 break;
		case 64: marks=3;
				 attendence=;
				 break;
		case 65: marks=5;
				 attendence=;
				 break;
		case 66: marks=3;
				 attendence=;
				 break;
		case 67: marks=5;
				 attendence=;
				 break;
		case 68: marks=6;
				 attendence=;
				 break;
		case 69: marks=0;
				 attendence=;
				 break;
		case 70: marks=0;
				 attendence=;
				 break;
		case 71: marks=7;
				 attendence=;
				 break;
		case 72: marks=4;
				 attendence=;
				 break;
		case 73: marks=5;
				 attendence=;
				 break;
		case 74: marks=9;
				 attendence=;
				 break;
		case 75: marks=5;
				 attendence=;
				 break;
		case 76: marks=4;
				 attendence=;
				 break;
		case 77: marks=8;
				 attendence=;
				 break;
		case 78: marks=6;
				 attendence=;
				 break;
		case 79: marks=5;
				 attendence=;
				 break;
		case 80: marks=2;
				 attendence=;
				 break;
		case 81: marks=0;
				 attendence=;
				 break;
		case 82: marks=7;
				 attendence=;
				 break;
		case 83: marks=6;
				 attendence=;
				 break;
		case 84: marks=3;
				 attendence=;
				 break;
		case 85: marks=5;
				 attendence=;
				 break;
		case 86: marks=6;
				 attendence=;
				 break;
		case 87: marks=6;
				 attendence=;
				 break;
		case 88: marks=10;
				 attendence=;
				 break;
		case 89: marks=9;
				 attendence=;
				 break;
		case 90: marks=0;
				 attendence=;
				 break;
		case 91: marks=10;
				 attendence=;
				 break;
		case 92: marks=9;
				 attendence=;
				 break;
		case 93: marks=8;
				 attendence=;
				 break;
		case 94: marks=7;
				 attendence=;
				 break;
		case 95: marks=9;
				 attendence=;
				 break;
		case 96: marks=5;
				 attendence=;
				 break;
		case 97: marks=0;
				 attendence=;
				 break;
		case 98: marks=7;
				 attendence=;
				 break;
		case 99: marks=0;
				 attendence=;
				 break;
		case 100:marks=5;
				 attendence=;
				 break;
		default :list_3(rollno);
	}
}