#include <stdio.h>
#include "marks_2.h"
int marks_1(int rollno)
{
	int roll=rollno;
	float marks=0;
	switch(roll)
	/*switch case check till rollno 50*/
	{
		case 1 : marks=6;
				 return(marks);
		case 2 : marks=7;
				 return(marks);
		case 3 : marks=8;
				 return(marks);
		case 4 : marks=9;
				 return(marks);
		case 5 : marks=10;
				 return(marks);
		case 6 : marks=8;
				 return(marks);
		case 7 : marks=7;
				 return(marks);
		case 8 : marks=9;
				 return(marks);
		case 9 : marks=5;
				 return(marks);
		case 10: marks=3;
				 return(marks);
		case 11: marks=0;
				 return(marks);
		case 12: marks=0;
				 return(marks);
		case 13: marks=5;
				 return(marks);
		case 14: marks=8;
				 return(marks);
		case 15: marks=7;
				 return(marks);
		case 16: marks=6;
				 return(marks);
		case 17: marks=10;
				 return(marks);
		case 18: marks=7;
				 return(marks);
		case 19: marks=8;
				 return(marks);
		case 20: marks=7;
				 return(marks);
		case 21: marks=6;
				 return(marks);
		case 22: marks=6;
				 return(marks);
		case 23: marks=0;
				 return(marks);
		case 24: marks=9;
				 return(marks);
		case 25: marks=5;
				 return(marks);
		case 26: marks=9;
				 return(marks);
		case 27: marks=5;
				 return(marks);
		case 28: marks=9;
				 return(marks);
		case 29: marks=0;
				 return(marks);
		case 30: marks=5;
				 return(marks);
		case 31: marks=8;
				 return(marks);
		case 32: marks=8;
				 return(marks);
		case 33: marks=2;
				 return(marks);
		case 34: marks=3;
				 return(marks);
		case 35: marks=4;
				 return(marks);
		case 36: marks=0;
				 return(marks);
		case 37: marks=8;
				 return(marks);
		case 38: marks=7;
				 return(marks);
		case 39: marks=6;
				 return(marks);
		case 40: marks=6;
				 return(marks);
		case 41: marks=2;
				 return(marks);
		case 42: marks=7;
				 return(marks);
		case 43: marks=7;
				 return(marks);
		case 44: marks=7;
				 return(marks);
		case 45: marks=5;
				 return(marks);
		case 46: marks=4;
				 return(marks);
		case 47: marks=6;
				 return(marks);
		case 48: marks=1;
				 return(marks);
		case 49: marks=0;
				 return(marks);
		case 50: marks=8;
				 return(marks);
		default :marks_2(rollno);
	}
}